[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
chrono = {version="0.4.19", features=["serde"]}
futures = "0.3.21"
mongodb = {version="2.2.1", features=["bson-serde_with", "bson-chrono-0_4"]}
serde = "1.0.137"
serde_json = "1.0.81"
